### ISSUE TITLE
Missing AC3 documentation improvements ☔ 

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#6711]
This issue tracks the docs items that weren't completed in https://github.com/apollographql/apollo-client/pull/6429.

**TODO:**

- [x] Refactor all pagination documentation
  - [x] ~Overhaul https://www.apollographql.com/docs/react/data/pagination/~
    * https://github.com/apollographql/apollo-client/pull/7175
- [x] ~Deprecate `fetchMode`'s `updateQuery`, replacing with field policies (https://github.com/apollographql/apollo-client/pull/6464)~ 
  - https://github.com/apollographql/apollo-client/issues/8915#issuecomment-1133021058
- [x] ~Explain what `keyArgs: false` does~
  * See https://deploy-preview-7175--apollo-client-docs.netlify.app/docs/react/pagination/key-args/
/6852#issuecomment-674984235)
- [x] `@apollo/client/core`, `@apollo/client/utilities`, `@apollo/client/testing`, `@apollo/client/cache`, etc. entry points
- [x] ~Properly explain how `cache.writeQuery/Fragment` broadcasting can be silenced using the `broadcast` option (and what the advantages are to doing so - reference: https://github.com/apollographql/apollo-client/pull/6288) 👉  https://github.com/apollographql/apollo-client/pull/9978~
 - [x] ~Explain how to use `cache.performTransaction()` to batch writes without broadcasting until they've all finished. `cache.batch` (introduced in https://github.com/apollographql/apollo-client/pull/7819) provides a better API and essentially wraps `performTransaction`, so it’s the one we should recommend people use. 👉 https://github.com/apollographql/apollo-client/pull/9987~
- [x] ~Document `merge: false` (e.g. https://github.com/apollographql/apollo-client/pull/6372#issuecomment-670593650) 👉  https://github.com/apollographql/apollo-client/pull/9969~
- [x] ~Document `useReactiveVar` (https://github.com/apollographql/apollo-client/pull/6867) 👉  #9906~
- [x] ~Document type policy inheritance, using `possibleTypes` (https://github.com/apollographql/apollo-client/pull/7065) 👉  #9905~
- [x] ~Document custom merge function support in type policies (https://github.com/apollographql/apollo-client/pull/7070)~
- [x] ~Explain how to properly test local state using `MockedProvider`, by passing a configured `cache` into `MockedProvider` itself (https://github.com/apollographql/apollo-client/issues/4532)  `PR` https://github.com/apollographql/apollo-client/pull/9867~
- [x] ~Remove deprecated language from dataIdFromObject #9817~
- [x] updateQuery documentation error #9832 
- [ ] Missing docs about aborted requests for V3 #9882 
- [ ] Potential Missing docs  for `MyQueryInterface` #9946
- [ ] Allow registering named fragments with InMemoryCache to support using ...FragmentName in queries without redeclaring FragmentName in every query #9764 
- [ ] Avoid letting defaultDataIdFromObject normalize objects with nullish ids  #9862

**Comment by Jamesdinnes** [comment]
Would be good to get some more clarification around testing especially around client directives and reactive variables.

**Comment by abdonrd** [comment]
Meanwhile where we can find information about pagination? Thanks!

**Comment by hwillson** [comment]
@abdonrd We're working on overhauling the main pagination section of the docs, but in the meantime you can find some details here: https://www.apollographql.com/docs/react/caching/cache-field-behavior/#handling-pagination

**Comment by tsnieman** [comment]
Regardless of whether #6619 is a bug or intended behavior, [this comment](https://github.com/apollographql/apollo-client/issues/6619#issuecomment-661902207) indicates a section of the documentation that could use some love to clarify intention WRT merging variables on mutate calls. Similarly, information about the change (if intentional) should also be conveyed in migration guides, changelogs, etc.

**Comment by JesseZomer** [comment]
I'm looking for documentation for local-only mutations. I see there's still a checkbox missing with the mutation example, but if someone could explain to me what I'm doing wrong, that would be great. 

Our application makes use of the old local resolvers. Now I want to 'update' them to typePolicies. My old resolver looked like:
```javascript
resolvers: {
         ....
        Mutation: {
           createCategorie(...)
        }
}
```
No I changed it to this typePolicy: 
```javascript
const inMemoryCache = new InMemoryCache({
    typePolicies: {
        Query: {
            fields: {
                ....
            },
        },
        Mutation: {
            fields: {
                createCategorie(...) {
                    console.log('in create');
                }
            }
        },
       ...
```
the mutation gets called like this:
```javascript 
gql`
 mutation createSCategorie(...) {
 createCategorie(...) @client
}`,
```
However the console.log never gets called. Is there something I'm missing?

**Comment by tsnieman** [comment]
I think [this issue about undefined old data when loading new data](https://github.com/apollographql/apollo-client/issues/6603) could use some love in the documentation / migration guides too.

**Comment by dmitry** [comment]
@JesseZomer I've stuck with the same problem. Probably you can help me with migration from local resolvers -> reactive variable?
Another problem related to this issue: https://github.com/apollographql/apollo-client/issues/6247

**Comment by JesseZomer** [comment]
@dmitry I didn't migrate from local mutation resolvers to reactive variables, but I threw away the local mutations and just did direct cache updates with read/writeQuery.

**Comment by lorensr** [comment]
> @apollo/client/core, @apollo/client/utilities, @apollo/client/testing, @apollo/client/cache, etc. entry points

Also link entry points. These imports are out of date: https://www.apollographql.com/docs/link/

**Comment by gbiryukov** [comment]
Example with [apollo cache reset to initial state](https://www.apollographql.com/docs/react/caching/advanced-topics/#resetting-the-store) also needs to be updated because it uses deprecated `apollo-link-state` to write defaults

**Comment by jpvajda** [comment]
If anyone is interested in helping update our documentation for these different features or improvement please feel free to submit a PR. Thank you!

**Comment by jpvajda** [comment]
Our next steps with this issue will be to:

1. Validate if these changes still need to be made, or if we've subsequently made changes later on that nullified these older changes.
2. Confirm which docs updates are still required. 
3. Work with the docs team on the improvements that need to be made.

**Comment by jpvajda** [comment]
We decided we'll break this issue up in a few weeks where we can have low effort, medium effort and larger effort docs changes in separate issues instead of one larger issue.

**Comment by jpvajda** [comment]
I'll work on breaking this out into separate tickets.

**Comment by jpvajda** [comment]
Tickets we broke out for the remaining work:

https://github.com/apollographql/apollo-client/issues/10176
https://github.com/apollographql/apollo-client/issues/10177
https://github.com/apollographql/apollo-client/issues/10178
